### ISSUE TITLE
client side routing does not work.

### ISSUE THREAD

**Issue by rahulsingh806080** [myogeshchavan97/express-static-serve#3]
Cannot GET /service of refresh

**Comment by myogeshchavan97** [comment]
@rahulsingh806080  can you please let me know what you are trying to do that is not working?

**Comment by myogeshchavan97** [comment]
@rahulsingh806080  If you're having routing added in your React app, you need to add the following code in `server/index.js` file.

```js
app.use((req, res, next) => {
  res.sendFile(path.join(__dirname, "..", "build", "index.html"));
});
```

after all your middlewares.

So your `server/index.js` file will look like this.

```js
const path = require("path");
const express = require("express");
const app = express(); // create express app

// add middlewares
app.use(express.static(path.join(__dirname, "..", "build")));
app.use(express.static("public"));

app.use((req, res, next) => {
  res.sendFile(path.join(__dirname, "..", "build", "index.html"));
});

// start express server on port 5000
app.listen(5000, () => {
  console.log("server started on port 5000");
});
```

So because we have started the server using Express App, when the request comes to the server for any route and route you're trying to access does not exist on the server-side, we will be sending the `index.html` file from the `build` folder so your client-side route will handle that and will display the client-side route page.

**Comment by myogeshchavan97** [comment]
@rahulsingh806080 changes merged into the master branch
